### ISSUE TITLE
Rewrite, remove application name setting, and reduce amount of dependencies 

### ISSUE THREAD

**Issue by xmantheman** [wr1ght/kodicord#3]
turns out it's actually considered API abuse to change the application name, aside from that I'm going to do some other improvements and make this not rely on any third party dependencies other than built-in ones.

**Comment by wr1ght** [comment]
https://github.com/wr1ght/kodicord/commit/e01e78750ba8399dfa23fef7d3acfc1700473849

**Comment by xmantheman** [comment]
**Completed on commit** https://github.com/wr1ght/kodicord/commit/e01e78750ba8399dfa23fef7d3acfc1700473849
